version: '3.8'

services:
  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - "3000:3000"
    env_file:
      - ./auth/.env
    depends_on:
      - mongo
    networks:
      - app-network
  
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "37017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  product:
    build: ./product
    container_name: product_service
    ports:
      - "3001:3001"
    env_file:
      - ./product/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  order:
    build: ./order
    container_name: order_service
    ports:
      - "3002:3002"
    env_file:
      - ./order/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway_service
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: