version: '3.8'

services:
  auth:
    build: ./auth
    container_name: auth_service
    ports:
      - "3000:3000"
    env_file:
      - ./auth/.env
    networks:
      - app-network

  product:
    build: ./product
    container_name: product_service
    ports:
      - "3001:3001"
    env_file:
      - ./product/.env
    networks:
      - app-network

  order:
    build: ./order
    container_name: order_service
    ports:
      - "3002:3002"
    env_file:
      - ./order/.env
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway_service
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order
    env_file:
      - ./api-gateway/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
